### ISSUE TITLE
AxiosError: Request failed with status code 503

### ISSUE THREAD

**Issue by DAIORANGE** [univeous/koishi-plugin-twitter-video-downloader#1]
![image](https://user-images.githubusercontent.com/28801505/203220749-914650d5-ce62-455f-9f25-cdf3db9ded8e.png)

`twvdhttps://twitter.com/i/status/1587910036621230080`
`https://twitter.com/strangestmedia/status/1587910036621230080?s=46&t=WoZhgbDb3jjRRx2ipybX4A`

试了两种方式都会在日志里显示503 bot是部署在家里的小型工作站上 路由器那边设置了科学上网

**Comment by univeous** [comment]
用到的api似乎挂掉了🤔
后面有空的话我会找其他的api试试
